#
# Makefile to use with SDL+emscripten
# See https://emscripten.org/docs/getting_started/downloads.html
# for installation instructions.
#
# This Makefile assumes you have loaded emscripten's environment.
# (On Windows, you may need to execute emsdk_env.bat or encmdprompt.bat ahead)
#
# Running `make -f Makefile.emscripten` will produce three files:
#  - web/index.html
#  - web/index.js
#  - web/index.wasm
#
# All three are needed to run the demo.

CC = emcc
CXX = em++
EXE = $(WEB_DIR)/index.html

SOURCE_DIR    = src
INCLUDE_DIR   = include
ASSETS_DIR    = assets
IMGUI_DIR     = lib/imgui
IMPLOT_DIR    = lib/implot
DISASM_DIR    = lib/disasm

# Source Files
SOURCES  = $(SOURCE_DIR)/main.cpp
SOURCES += $(SOURCE_DIR)/rv32.cpp $(SOURCE_DIR)/emu.cpp $(SOURCE_DIR)/loader.cpp $(SOURCE_DIR)/app.cpp $(SOURCE_DIR)/net.cpp $(SOURCE_DIR)/headless.cpp $(SOURCE_DIR)/plic.cpp $(SOURCE_DIR)/virtio_net.cpp $(SOURCE_DIR)/usernet.cpp $(SOURCE_DIR)/netsetup.cpp
# ImGui Files
SOURCES += $(IMGUI_DIR)/imgui.cpp $(IMGUI_DIR)/imgui_demo.cpp $(IMGUI_DIR)/imgui_draw.cpp $(IMGUI_DIR)/imgui_tables.cpp $(IMGUI_DIR)/imgui_widgets.cpp
SOURCES += $(IMGUI_DIR)/backends/imgui_impl_sdl2.cpp $(IMGUI_DIR)/backends/imgui_impl_opengl3.cpp
# ImPlot Files
SOURCES += $(IMPLOT_DIR)/implot.cpp $(IMPLOT_DIR)/implot_items.cpp $(IMPLOT_DIR)/implot_demo.cpp
# Disasm Files
SOURCES += $(DISASM_DIR)/disasm.cpp

OBJS = $(addprefix $(WEB_DIR)/, $(addsuffix .o, $(basename $(notdir $(SOURCES)))))

UNAME_S := $(shell uname -s)

CPPFLAGS =
LDFLAGS =
EMS =

# XLEN=32 (default) builds web/, XLEN=64 builds web64/ (RV64IMAFD + Sv39 core)
XLEN ?= 32
ifeq ($(XLEN),64)
WEB_DIR ?= web64
CPPFLAGS += -DXLEN=64
else
WEB_DIR ?= web
endif

##---------------------------------------------------------------------
## EMSCRIPTEN OPTIONS
##---------------------------------------------------------------------

# ("EMS" options gets added to both CPPFLAGS and LDFLAGS, whereas some options are for linker only)
EMS += -s USE_SDL=2
EMS += -s DISABLE_EXCEPTION_CATCHING=1
EMS += -DIMGUI_IMPL_OPENGL_ES2
# The Emulator object (CSR file etc.) lives on the stack; RV64 needs more than the 64 KB default
LDFLAGS += -s STACK_SIZE=1048576
LDFLAGS += -s WASM=1 -s ALLOW_MEMORY_GROWTH=1 -s NO_EXIT_RUNTIME=0 -s ASSERTIONS=1 -s ERROR_ON_UNDEFINED_SYMBOLS=0

# Build as single file (binary text encoded in .html file)
#LDFLAGS += -sSINGLE_FILE

# Uncomment next line to fix possible rendering bugs with Emscripten version older then 1.39.0 (https://github.com/ocornut/imgui/issues/2877)
#EMS += -s BINARYEN_TRAP_MODE=clamp
#EMS += -s SAFE_HEAP=1    ## Adds overhead

# Emscripten allows preloading a file or folder to be accessible at runtime.
# The Makefile for this example project suggests embedding the misc/fonts/ folder into our application, it will then be accessible as "/fonts"
# See documentation for more details: https://emscripten.org/docs/porting/files/packaging_files.html
# (Default value is 0. Set to 1 to enable file-system and include the misc/fonts/ folder as part of the build.)
USE_FILE_SYSTEM ?= 1
ifeq ($(USE_FILE_SYSTEM), 0)
LDFLAGS += -s NO_FILESYSTEM=1
CPPFLAGS += -DIMGUI_DISABLE_FILE_FUNCTIONS
endif
ifeq ($(USE_FILE_SYSTEM), 1)
LDFLAGS += --no-heap-copy --preload-file $(ASSETS_DIR)@/assets --exclude-file "*/isa-test-rv64*"
# Ship only the Linux image for the selected XLEN (rv64 = OpenSBI + Sv39 kernel, ~30 MB)
ifeq ($(XLEN),64)
LDFLAGS += --exclude-file "*/linux/*" --exclude-file "*/isa-test/*" --exclude-file "*/kernel-Image" --exclude-file "*/fw_jump.bin"
else
LDFLAGS += --exclude-file "*/linux64*"
endif
endif

##---------------------------------------------------------------------
## FINAL BUILD FLAGS
##---------------------------------------------------------------------

CPPFLAGS += -I$(SOURCE_DIR) -I$(INCLUDE_DIR)
CPPFLAGS += -I$(IMGUI_DIR) -I$(IMGUI_DIR)/backends -I$(IMGUI_DIR)/examples/libs/emscripten
CPPFLAGS += -I$(IMPLOT_DIR) -I$(DISASM_DIR)
#CPPFLAGS += -g
CPPFLAGS += -Wall -Wformat -Os $(EMS)
CXXFLAGS += -std=c++17
# track header dependencies so editing a header rebuilds the objects that include it
CXXFLAGS += -MMD -MP
LDFLAGS += --shell-file $(IMGUI_DIR)/examples/libs/emscripten/shell_minimal.html
LDFLAGS += $(EMS)

##---------------------------------------------------------------------
## BUILD RULES
##---------------------------------------------------------------------

$(WEB_DIR):
	mkdir $@

$(WEB_DIR)/%.o: %.cpp | $(WEB_DIR)
	$(CXX) $(CPPFLAGS) $(CXXFLAGS) -c -o $@ $<

$(WEB_DIR)/%.o: $(SOURCE_DIR)/%.cpp | $(WEB_DIR)
	$(CXX) $(CPPFLAGS) $(CXXFLAGS) -c -o $@ $<

$(WEB_DIR)/%.o: $(IMGUI_DIR)/%.cpp | $(WEB_DIR)
	$(CXX) $(CPPFLAGS) $(CXXFLAGS) -c -o $@ $<

$(WEB_DIR)/%.o: $(IMGUI_DIR)/backends/%.cpp | $(WEB_DIR)
	$(CXX) $(CPPFLAGS) $(CXXFLAGS) -c -o $@ $<

$(WEB_DIR)/%.o: $(IMPLOT_DIR)/%.cpp | $(WEB_DIR)
	$(CXX) $(CPPFLAGS) $(CXXFLAGS) -c -o $@ $<

$(WEB_DIR)/%.o: $(DISASM_DIR)/%.cpp | $(WEB_DIR)
	$(CXX) $(CPPFLAGS) $(CXXFLAGS) -c -o $@ $<

all: $(EXE)
	@echo Build complete for $(EXE)

serve: all
	python3 -m http.server -d $(WEB_DIR)

$(EXE): $(OBJS)
	$(CXX) -o $@ $(OBJS) $(LDFLAGS)

##---------------------------------------------------------------------
## WASM ISA TEST RUNNER (Node.js)
## Compiles the emulator core (no GUI) to WebAssembly and runs it under Node so
## the ISA suites can be executed against the wasm build:
##   make -f Makefile.emscripten isas-wasm            (RV32)
##   make -f Makefile.emscripten XLEN=64 isas-wasm    (RV64, -p- tests)
##---------------------------------------------------------------------
ISA_JS = $(WEB_DIR)/isa.js
ISA_OBJS = $(addprefix $(WEB_DIR)/, rv32.o emu.o loader.o net.o headless.o plic.o virtio_net.o usernet.o netsetup.o wasm_isa_main.o disasm.o)

$(ISA_JS): $(ISA_OBJS)
	$(CXX) -o $@ $(ISA_OBJS) -s ENVIRONMENT=node -s NODERAWFS=1 -s EXIT_RUNTIME=1 \
		-s ALLOW_MEMORY_GROWTH=1 -s DISABLE_EXCEPTION_CATCHING=1 -s ERROR_ON_UNDEFINED_SYMBOLS=0 \
		-s STACK_SIZE=1048576

isa-wasm: $(ISA_JS)

ISA_TEST_DIR ?= $(ASSETS_DIR)/isa-test
ifeq ($(XLEN),64)
ISA_TEST_DIR = $(ASSETS_DIR)/isa-test-rv64
endif

isas-wasm: $(ISA_JS)
	SKIPFILE=../scripts/isa_skip_wasm.txt ../scripts/run_isa.sh "node $(ISA_JS)" $(ISA_TEST_DIR)

clean:
	rm -rf $(WEB_DIR)

-include $(wildcard $(WEB_DIR)/*.d)
